[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "cryosiam"
version = "1.0"
description = "CryoSiam: Deep Learning-based Cryo-ET Analysis"
readme = "README.md"
requires-python = ">=3.8"
license = { text = "GPL-3.0-only" }
authors = [
    { name = "Frosina Stojanovska", email = "stojanovska.frose@gmail.com" }
]
dependencies = [
    "edt",
    "h5py",
    "itk",
    "lightning",
    "matplotlib",
    "monai>=1.3.1",
    "mrcfile",
    "numpy",
    "open3d",
    "pandas",
    "Pillow",
    "plotly",
    "python-elf",
    "PyYAML",
    "scikit-learn",
    "scikit-image",
    "scipy",
    "torch>=2.1.0",
    "torchvision",
    "pytorch3d",
    "starfile",
    "tqdm",
    "umap-learn"
]

[project.scripts]
cryosiam = "cryosiam.cli:main"
